# Generated by Django 3.2.4 on 2021-07-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistZoneAdministration', '0003_imagenesindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenesindex',
            name='titulo',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
