# Generated by Django 3.2.4 on 2021-07-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistZoneAdministration', '0004_imagenesindex_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesIndex1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesIndex2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='imagenes')),
            ],
        ),
    ]
