# Generated by Django 3.2.4 on 2021-07-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuadro', models.CharField(max_length=30)),
                ('nombre_autor', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
