# Generated by Django 3.2.4 on 2021-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistZoneApp', '0002_publicaciones_imagen_cuadro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
            ],
        ),
    ]
