# Generated by Django 3.2.4 on 2021-07-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistZoneApp', '0003_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contrasenna',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
