# Generated by Django 3.2.4 on 2021-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtistZoneApp', '0004_usuarios_contrasenna'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
